### ISSUE TITLE
log-list.json: Invalid response 404

### ISSUE THREAD

**Issue by Vitanio** [appmattus/certificatetransparency#57] opened 2023-02-16 08:27 UTC
Hi,
In date (15/02/2023), i've faced the following issue with certificate transparency:

```
- javax.net.ssl.SSLPeerUnverifiedException: Certificate transparency failed
Failure: Unable to load log servers with log-list.json failed to load with java.io.IOException: Invalid response 404
```

Seems that the library makes some network call to services not always available. 
This is a huge problem on apps that relies on network calls using this lib.
May i ask you when and why is this problem  verified?

Info:
lib version:1.1.1

**Comment by dixitpTheaa** [comment] 2023-02-16 09:31
@Vitanio the issue is already been raised you can check here: https://github.com/appmattus/certificatetransparency/issues/55

**Comment by Vitanio** [comment] 2023-02-16 15:00
The issue was: 
https://groups.google.com/a/chromium.org/g/ct-policy/c/zejEtWAJtEA

**Comment by mattmook** [comment] 2023-03-06 09:51
Closing as duplicate of #54

**Closed by mattmook** 2023-03-06 09:51 UTC
