### ISSUE TITLE
Google removed V2 log lists today (90 day window after the 10-17-22 deadline)

### ISSUE THREAD

**Issue by MatthewWhitmer** [appmattus/certificatetransparency#55] opened 2023-02-15 14:45 UTC
This library no longer functions and is completely broken out of the box, v3 log lists need to be used instead of v2.

https://groups.google.com/a/chromium.org/g/ct-policy/c/zejEtWAJtEA/m/fX_AG-HUAQAJ

**Comment by barnhill** [comment] 2023-02-15 15:18
Same issue here today affecting production

**Comment by bhm** [comment] 2023-02-15 15:23
Same issue here. Work around found in other threads does not appear to be a golden bullet.

**Comment by VictorGuedes** [comment] 2023-02-15 15:26
Same here. Any suggestion?

**Comment by rakesh-diagnal** [comment] 2023-02-15 15:31
The change is been reverted as informed here:
https://groups.google.com/a/chromium.org/g/ct-policy/c/zejEtWAJtEA/m/muzgKtcaBQAJ
<img width="1223" alt="Screenshot 2023-02-15 at 9 01 10 PM" src="https://user-images.githubusercontent.com/76932568/219073581-51c09682-6042-4edf-b89e-a7580aaa2f7c.png">

**Comment by rakexg** [comment] 2023-02-15 15:53
> since it is (only) mentioned in this group and with the 90 days grace period until today

There was a message shown in the google play store for the apps using this library when a new release was been made. Most of the apps might not have made an update during this time period to notice the play store error. 

For now if this library is continued to use, a workaround has been shared in the message to use with this library.
<img width="960" alt="Screenshot 2023-02-15 at 9 19 46 PM" src="https://user-images.githubusercontent.com/12766121/219079177-4e643d35-01f0-4b5b-bf17-18b3f931e323.png">

Workaround url: https://github.com/appmattus/certificatetransparency/issues/44#issuecomment-1253781622

**Comment by phbnf** [comment] 2023-02-15 20:09
It should also be possible to disable CT enforcement on all hosts with:

```
certificateTransparencyInterceptor {
        excludeHost("*.*")
}
```

Thanks @roger2hk for providing this snippet.

**Comment by jdeblasio** [comment] 2023-02-15 20:16
To add on to what @phbnf said, I'd encourage you to strongly consider this approach (or stop using this library entirely) instead of simply updating to the v3 URL.

Just switching to the v3 list leaves you reliant on an unmaintained library that isn't tracking any further changes that may impact your app. If you decide to update to the v3 list, you should also commit to monitoring the relevant CT mailing lists for changes that might affect your app so long as your app uses the library.

See my further comment at https://github.com/appmattus/certificatetransparency/issues/54#issuecomment-1431880499

**Comment by roger2hk** [comment] 2023-02-15 22:26
The previous snippet I provided was not correct. Please use the minus operator.

```kotlin
installCertificateTransparencyProvider {
    // Exclude all domains
    -"*.*"
}
```

```kotlin
certificateTransparencyInterceptor {
    // Exclude all domains
    -"*.*"
}
```

**Comment by roger2hk** [comment] 2023-02-17 00:56
> > It should also be possible to disable CT enforcement on all hosts with:
> > ```
> > certificateTransparencyInterceptor {
> >         excludeHost("*.*")
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks @roger2hk for providing this snippet.
> 
> why add it if you disable it for everything? 🧐 🤷

This snippet is provided for apps tightly coupled with this library to quickly disable the CT enforcement and avoid app breakage after v2 log list turndown. If the app developer insists to disable CT enforcement, removing the entire library dependency is definitely the way to go.

**Comment by mattmook** [comment] 2023-03-06 09:50
A new version will be released shortly that will address the URL change and also provide a more robust caching mechanism.

Of particular note there are now some different VerificationResults to take note of that can help from a monitoring point of view.

VerificationResult.Success.StaleNetwork - This indicates that the timestamp of the log-list.json file from the network is out of date. There are two cases here:
either there is already cached data that is newer than the server is presenting; possible replay attack
or there is no cached data and we are returning the server data as presented; possible network issues
VerificationResult.DisableChecks - This indicates we are unable to load new data from the server and the data we do have is greater than 70 days old so (like Chrome) we are failing soft and disabling CT checks.

**Comment by mattmook** [comment] 2023-03-06 09:50
Closing this issue as a duplicate of #54

**Closed by mattmook** 2023-03-06 09:50 UTC
