### ISSUE TITLE
Didn't find class "java.time.Duration"

### ISSUE THREAD

**Issue by Vitanio** [appmattus/certificatetransparency#91] opened 2023-05-16 13:29 UTC
Hi,
in the last few days i noticed this new crash on my analytics. 
It is a known issue? 

I attach the stack here below:

> Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.app-1/base.apk"],nativeLibraryDirectories=[/data/app/app/lib/arm64, /data/app/com.app-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.appmattus.certificatetransparency.loglist.LogListCacheManagementDataSource.<clinit>(LogListCacheManagementDataSource.kt:137)
       at com.appmattus.certificatetransparency.loglist.LogListDataSourceFactory.createDataSource(LogListDataSourceFactory.kt:127)
       at com.appmattus.certificatetransparency.loglist.LogListDataSourceFactory.createDataSource$default(LogListDataSourceFactory.kt:119)
       at com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyBase.<init>(CertificateTransparencyBase.kt:78)
       at com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyInterceptor.<init>(CertificateTransparencyInterceptor.kt:50)
       at com.appmattus.certificatetransparency.CTInterceptorBuilder.build(CTInterceptorBuilder.kt:252)
       at com.appmattus.certificatetransparency.CTInterceptorBuilderExtKt.certificateTransparencyInterceptor(CTInterceptorBuilderExt.kt:35)
       at com.sitael.vending.di.NetworkModule.provideOkHttpClient(NetworkModule.kt:71)
       at com.sitael.vending.di.NetworkModule_ProvideOkHttpClientFactory.provideOkHttpClient(NetworkModule_ProvideOkHttpClientFactory.java:47)
       at com.sitael.vending.DaggerSmartVendingApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerSmartVendingApplication_HiltComponents_SingletonC.java:2291)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.sitael.vending.DaggerSmartVendingApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerSmartVendingApplication_HiltComponents_SingletonC.java:2288)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.sitael.vending.DaggerSmartVendingApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerSmartVendingApplication_HiltComponents_SingletonC.java:2285)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.sitael.vending.DaggerSmartVendingApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerSmartVendingApplication_HiltComponents_SingletonC.java:2330)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.sitael.vending.DaggerSmartVendingApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get0(DaggerSmartVendingApplication_HiltComponents_SingletonC.java:1904)
       at com.sitael.vending.DaggerSmartVendingApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerSmartVendingApplication_HiltComponents_SingletonC.java:2076)
       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:104)
       at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:89)
       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:116)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
       at com.sitael.vending.ui.main_page.home.HomePageFragment.getViewModel(HomePageFragment.kt:105)
       at com.sitael.vending.ui.main_page.home.HomePageFragment.observeViewModel(HomePageFragment.kt:397)
       at com.sitael.vending.ui.main_page.home.HomePageFragment.onViewCreated(HomePageFragment.kt:178)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976)
       at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2879)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
       at android.app.Activity.performStart(Activity.java:6935)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6517)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

Thank you for your support,
VD

**Comment by mattmook** [comment] 2023-05-17 21:44
Duplicate of #85 You need to enable desugaring - see https://developer.android.com/studio/write/java8-support#library-desugaring for more information

**Closed by mattmook** 2023-05-17 21:44 UTC
